
/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 3299;
const int acc_off_y = -411;
const int acc_off_z = 5569;
const float acc_scale_x = 4374.63952677;
const float acc_scale_y = 17353.5204127;
const float acc_scale_z = 0;

const int magn_off_x = 3306;
const int magn_off_y = -390;
const int magn_off_z = 5582;
const float magn_scale_x = 4372.29331372;
const float magn_scale_y = 17283.7082982;
const float magn_scale_z = 0;
