# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoTest.ui'
#
# Created: Sat Dec 27 00:00:44 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VoTest(object):
    def setupUi(self, VoTest_i):
        VoTest_i.setObjectName("VoTest")
        VoTest_i.resize(800, 600)
        VoTest_i.setMinimumSize(QtCore.QSize(800, 600))
        VoTest_i.setMaximumSize(QtCore.QSize(800, 600))
        VoTest_i.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(VoTest_i)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PID = QtGui.QGroupBox(self.gridLayoutWidget)
        self.PID.setObjectName("PID")
        self.PID.setCheckable(True)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.PID)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 361, 241))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.baseThrustVal = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baseThrustVal.setFont(font)
        self.baseThrustVal.setObjectName("baseThrustVal")
        self.verticalLayout_8.addWidget(self.baseThrustVal)
        self.baseThrust = QtGui.QSlider(self.verticalLayoutWidget_7)
        self.baseThrust.setOrientation(QtCore.Qt.Vertical)
        self.baseThrust.setObjectName("baseThrust")
        self.baseThrust.setMaximum(255)
        self.baseThrust.setMinimum(0)
        self.verticalLayout_8.addWidget(self.baseThrust)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_8.addWidget(self.label_29)
        self.horizontalLayout_23.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.yawOut = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.yawOut.setEnabled(True)
        self.yawOut.setReadOnly(True)
        self.yawOut.setObjectName("yawOut")
        self.horizontalLayout_25.addWidget(self.yawOut)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(10)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_35 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_30.addWidget(self.label_35)
        self.pitchOut = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.pitchOut.setEnabled(True)
        self.pitchOut.setReadOnly(True)
        self.pitchOut.setObjectName("pitchOut")
        self.horizontalLayout_30.addWidget(self.pitchOut)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_34 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_29.addWidget(self.label_34)
        self.rollOut = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.rollOut.setEnabled(True)
        self.rollOut.setReadOnly(True)
        self.rollOut.setObjectName("rollOut")
        self.horizontalLayout_29.addWidget(self.rollOut)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.gridLayout.addWidget(self.PID, 1, 0, 1, 1)
        self.MotorsTest = QtGui.QGroupBox(self.gridLayoutWidget)
        self.MotorsTest.setObjectName("MotorsTest")
        self.MotorsTest.setCheckable(True)
        self.verticalLayoutWidget = QtGui.QWidget(self.MotorsTest)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.m1Val = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m1Val.setFont(font)
        self.m1Val.setObjectName("m1Val")
        self.verticalLayout_2.addWidget(self.m1Val)
        self.m1 = QtGui.QSlider(self.verticalLayoutWidget)
        self.m1.setOrientation(QtCore.Qt.Vertical)
        self.m1.setObjectName("m1")
        self.verticalLayout_2.addWidget(self.m1)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.m2Val = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m2Val.setFont(font)
        self.m2Val.setObjectName("m2Val")
        self.verticalLayout_3.addWidget(self.m2Val)
        self.m2 = QtGui.QSlider(self.verticalLayoutWidget)
        self.m2.setOrientation(QtCore.Qt.Vertical)
        self.m2.setObjectName("m2")
        self.verticalLayout_3.addWidget(self.m2)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.m3Val = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m3Val.setFont(font)
        self.m3Val.setObjectName("m3Val")
        self.verticalLayout_4.addWidget(self.m3Val)
        self.m3 = QtGui.QSlider(self.verticalLayoutWidget)
        self.m3.setOrientation(QtCore.Qt.Vertical)
        self.m3.setObjectName("m3")
        self.verticalLayout_4.addWidget(self.m3)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.m4Val = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m4Val.setFont(font)
        self.m4Val.setObjectName("m4Val")
        self.verticalLayout_5.addWidget(self.m4Val)
        self.mVal = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mVal.setFont(font)
        self.mVal.setObjectName("mVal")
        self.verticalLayout_6.addWidget(self.mVal)
        self.m4 = QtGui.QSlider(self.verticalLayoutWidget)
        self.m4.setOrientation(QtCore.Qt.Vertical)
        self.m4.setObjectName("m4")

        self.m = QtGui.QSlider(self.verticalLayoutWidget)
        self.m.setOrientation(QtCore.Qt.Vertical)
        self.m.setObjectName("m")
        
        self.m1.setMaximum(255)
        self.m1.setMinimum(0)
        self.m2.setMaximum(255)
        self.m2.setMinimum(0)
        self.m3.setMaximum(255)
        self.m3.setMinimum(0)
        self.m4.setMaximum(255)
        self.m4.setMinimum(0)
        self.m.setMaximum(255)
        self.m.setMinimum(0)
        
        self.verticalLayout_5.addWidget(self.m4)
        self.verticalLayout_6.addWidget(self.m)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.MotorsTest, 0, 0, 1, 1)
        self.RawValues = QtGui.QGroupBox(self.gridLayoutWidget)
        self.RawValues.setObjectName("RawValues")
        self.RawValues.setCheckable(True)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.RawValues)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(9, 19, 361, 252))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(14)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.gyroX = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.gyroX.setEnabled(True)
        self.gyroX.setReadOnly(True)
        self.gyroX.setObjectName("gyroX")
        self.horizontalLayout_3.addWidget(self.gyroX)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.accX = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.accX.setEnabled(True)
        self.accX.setReadOnly(True)
        self.accX.setObjectName("accX")
        self.horizontalLayout_11.addWidget(self.accX)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.magX = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.magX.setEnabled(True)
        self.magX.setReadOnly(True)
        self.magX.setObjectName("magX")
        self.horizontalLayout_14.addWidget(self.magX)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.temp = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.temp.setEnabled(True)
        self.temp.setReadOnly(True)
        self.temp.setObjectName("temp")
        self.horizontalLayout_16.addWidget(self.temp)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.gyroY = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.gyroY.setEnabled(True)
        self.gyroY.setReadOnly(True)
        self.gyroY.setObjectName("gyroY")
        self.horizontalLayout_10.addWidget(self.gyroY)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.accY = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.accY.setEnabled(True)
        self.accY.setReadOnly(True)
        self.accY.setObjectName("accY")
        self.horizontalLayout_12.addWidget(self.accY)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.gyroZ = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.gyroZ.setEnabled(True)
        self.gyroZ.setReadOnly(True)
        self.gyroZ.setObjectName("gyroZ")
        self.horizontalLayout_4.addWidget(self.gyroZ)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.accZ = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.accZ.setEnabled(True)
        self.accZ.setReadOnly(True)
        self.accZ.setObjectName("accZ")
        self.horizontalLayout_13.addWidget(self.accZ)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_13)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.magY = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.magY.setEnabled(True)
        self.magY.setReadOnly(True)
        self.magY.setObjectName("magY")
        self.horizontalLayout_15.addWidget(self.magY)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.motionDetect = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.motionDetect.setEnabled(True)
        self.motionDetect.setReadOnly(True)
        self.motionDetect.setObjectName("motionDetect")
        self.horizontalLayout_17.addWidget(self.motionDetect)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_17)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 5, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(10)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_20.addWidget(self.label_27)
        self.magZ = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.magZ.setEnabled(True)
        self.magZ.setReadOnly(True)
        self.magZ.setObjectName("magZ")
        self.horizontalLayout_20.addWidget(self.magZ)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_21.addWidget(self.label_28)
        self.libVer = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.libVer.setEnabled(True)
        self.libVer.setReadOnly(True)
        self.libVer.setObjectName("libVer")
        self.horizontalLayout_21.addWidget(self.libVer)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 6, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.RawValues, 0, 2, 1, 1)
        VoTest_i.setCentralWidget(self.centralwidget)

        self.retranslateUi(VoTest_i)
        QtCore.QMetaObject.connectSlotsByName(VoTest_i)

    def retranslateUi(self, VoTest_i):
        VoTest_i.setWindowTitle(QtGui.QApplication.translate("VoTest_i", "VoPilot - VoCopter Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.PID.setTitle(QtGui.QApplication.translate("VoTest_i", "PID", None, QtGui.QApplication.UnicodeUTF8))
        self.baseThrustVal.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("VoTest_i", "Base Thrust", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("VoTest_i", "Yaw Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("VoTest_i", "Pitch Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("VoTest_i", "Roll Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.MotorsTest.setTitle(QtGui.QApplication.translate("VoTest_i", "Motors", None, QtGui.QApplication.UnicodeUTF8))
        self.m1Val.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VoTest_i", "M1", None, QtGui.QApplication.UnicodeUTF8))
        self.m2Val.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VoTest_i", "M2", None, QtGui.QApplication.UnicodeUTF8))
        self.m3Val.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VoTest_i", "M3", None, QtGui.QApplication.UnicodeUTF8))
        self.m4Val.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.mVal.setText(QtGui.QApplication.translate("VoTest_i", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VoTest_i", "M4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VoTest_i", "Base Thrust", None, QtGui.QApplication.UnicodeUTF8))
        self.RawValues.setTitle(QtGui.QApplication.translate("VoTest_i", "FreeIMU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("VoTest_i", "Gyro X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("VoTest_i", "Acc X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("VoTest_i", "Mag X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("VoTest_i", "Temprature:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("VoTest_i", "Gyro Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("VoTest_i", "Acc Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("VoTest_i", "Gyro Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("VoTest_i", "Acc Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("VoTest_i", "Mag Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("VoTest_i", "Motion Detect:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("VoTest_i", "Mag Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("VoTest_i", "Library Version:", None, QtGui.QApplication.UnicodeUTF8))
